apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: develop-gprod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: develop-gprod
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: Anashamoyadusha
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: gprod_dev
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: develop-gprod
spec:
  selector:
    app: db
  ports:
  - port: 5432
    targetPort: 5432
