version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gprod
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    command: npm run start:prod
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  pgdata: 