services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gprod
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gp-network
  app:
    build: .
    command: sh /app/docker-entrypoint.sh
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - gp-network
  # Сервис для e2e-тестов
  e2e:
    container_name: e2e
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gprod
      - NODE_ENV=test
    networks:
      - gp-network
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm test:e2e -- --runInBand
volumes:
  pgdata: 

networks:
  gp-network:
    driver: bridge 