services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gprod
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    command: sh /app/docker-entrypoint.sh
    ports:
      - "3007:3007"
    env_file:
      - .env
    depends_on:
      - db
  test:
    build: .
    command: pnpm run test:e2e:ci
    environment:
      - BASE_URL=http://app:3007
    depends_on:
      - app
    env_file:
      - .env
volumes:
  pgdata: 