version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - NODE_ENV=development
      - DEV_DATABASE_URL=postgresql://postgres:postgres@db:5432/devdb
      - DEV_JWT_SECRET=devsecret
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: always
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
volumes:
  pgdata-dev: 