version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:prod
    environment:
      - NODE_ENV=production
      - PROD_DATABASE_URL=postgresql://postgres:postgres@db:5432/proddb
      - PROD_JWT_SECRET=prodsecret
    ports:
      - '3000:3000'
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: proddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
volumes:
  pgdata-prod: 