version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gprod-db-stage
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-gprod_stage}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: gprod-app-stage
    build:
      context: ../
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/gprod_stage}
      NODE_ENV: ${NODE_ENV:-staging}
    ports:
      - '3003:3000'
    volumes:
      - ../:/app
      - /app/node_modules
    command: sh -c "pnpm prisma generate && pnpm prisma migrate deploy && pnpm start:stage"

  prometheus:
    image: prom/prometheus:latest
    container_name: gprod-prometheus-stage
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ../../prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    container_name: gprod-grafana-stage
    restart: always
    ports:
      - '3100:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  postgres_data_stage:
    name: gprod-postgres-stage-data
  prometheus_data:
    name: gprod-prometheus-stage-data
  grafana_data:
    name: gprod-grafana-stage-data 