apiVersion: v1
kind: Service
metadata:
  name: gprod-backend
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: gprod-backend
