image:
  repository: ghcr.io/themacroeconomicdao/gprod-backend
  tag: dev

env:
  NODE_ENV: development
  PORT: 3000
  LOG_LEVEL: debug
  CORS_ENABLED: "true"
  CORS_ORIGIN: "https://dev.gprod.build.infra.gyber.org,https://api.dev.gprod.build.infra.gyber.org,https://localhost:3000"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX: "1000"
  APP_NAME: "GPROD API DEV"
  APP_VERSION: "1.0.0-dev"
  DOMAIN: "api.dev.gprod.build.infra.gyber.org"
  SUPPORT_EMAIL: "support@gprod.org"
  JWT_EXPIRES: "1h"
  JWT_REFRESH_EXPIRES: "30d"

secretEnv:
  DATABASE_URL: "postgresql://postgres:Anashamoyadusha@db:5432/gprod_dev"
  POSTGRES_PASSWORD: "Anashamoyadusha"
  POSTGRES_HOST: "db"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "gprod_dev"
  JWT_SECRET: "Anashamoyadusha"
  TEST_JWT_SECRET: "Anashamoyadusha"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "Anashamoyadusha"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "Anashamoyadusha"

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: api.dev.gprod.build.infra.gyber.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - api.dev.gprod.build.infra.gyber.org
      secretName: gprod-dev-tls

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"

imagePullSecrets:
  - name: ghcr
