# ENV централизовано
env:
  HEALTHCHECK_URL: https://api.dev.gprod.build.infra.gyber.org/api/v1/health
  NAMESPACE: gprod
  IMAGE_TAG: latest

name: CI/CD Pipeline

on:
  push:
    branches: [main]
  schedule:
    - cron: '*/10 * * * *' # каждые 10 минут

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run test
      - run: pnpm run test:e2e

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3.2.0
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - run: docker build -t ghcr.io/themacroeconomicdao/gprod-backend:${{ env.IMAGE_TAG }} .
      - run: docker push ghcr.io/themacroeconomicdao/gprod-backend:${{ env.IMAGE_TAG }}

  migrate:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - run: pnpm install
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
      - name: Run Prisma Migrate
        run: |
          set -e
          kubectl exec deploy/gprod-backend -- npx prisma migrate deploy

  deploy:
    runs-on: ubuntu-latest
    needs: migrate
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
      - uses: azure/setup-helm@v4.1.0
      - name: Helm dry-run
        run: helm upgrade --install gprod-backend ./helm/gprod-backend --namespace ${{ env.NAMESPACE }} --values ./helm/gprod-backend/values-dev.yaml --set image.tag=${{ env.IMAGE_TAG }} --dry-run
      - name: Deploy with Helm
        run: |
          helm upgrade --install gprod-backend ./helm/gprod-backend \
            --namespace ${{ env.NAMESPACE }} \
            --values ./helm/gprod-backend/values-dev.yaml \
            --set image.tag=${{ env.IMAGE_TAG }}

  healthcheck:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
      - name: Wait for rollout
        run: timeout 180s kubectl rollout status deployment/gprod-backend -n ${{ env.NAMESPACE }} --timeout=120s
      - name: Healthcheck
        id: health
        run: |
          RESPONSE=$(bash automation/scripts/healthcheck.sh ${{ env.HEALTHCHECK_URL }})
          echo "response=$RESPONSE" >> $GITHUB_OUTPUT
      - name: Telegram Notify (Success)
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ Деплой успешен!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Коммит: ${{ github.sha }}
            Автор: ${{ github.actor }}
            Подробнее: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Ответ healthcheck: ${{ steps.health.outputs.response }}
      - name: Telegram Notify (Failure)
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ Ошибка деплоя!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Коммит: ${{ github.sha }}
            Автор: ${{ github.actor }}
            Подробнее: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Ответ healthcheck: ${{ steps.health.outputs.response }}

  rollback:
    if: failure() && needs.healthcheck.result == 'failure'
    runs-on: ubuntu-latest
    needs: healthcheck
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
      - uses: azure/setup-helm@v4.1.0
      - name: Get previous release
        id: prev_release
        run: |
          REV=$(helm history gprod-backend --namespace ${{ env.NAMESPACE }} | awk 'NR>1 {print $1}' | sort -nr | sed -n 2p)
          echo "rev=$REV" >> $GITHUB_OUTPUT
      - name: Rollback Helm release
        run: helm rollback gprod-backend ${{ steps.prev_release.outputs.rev }} --namespace ${{ env.NAMESPACE }}
      - name: Telegram Notify (Rollback)
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ⚠️ Выполнен rollback!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Откат на релиз: ${{ steps.prev_release.outputs.rev }}
            Подробнее: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  periodic-healthcheck:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Healthcheck
        id: health
        run: |
          RESPONSE=$(bash automation/scripts/healthcheck.sh ${{ env.HEALTHCHECK_URL }})
          echo "response=$RESPONSE" >> $GITHUB_OUTPUT
      - name: Telegram Notify (Failure)
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ Периодический healthcheck не прошёл!
            Репозиторий: ${{ github.repository }}
            Подробнее: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Ответ healthcheck: ${{ steps.health.outputs.response }}